on:
  push:
    branches:
      - '*'
    tags:
      - '*'
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.version-matrix.outputs.matrix }}
      latest: ${{ steps.latest.outputs.latest }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version-matrix
        run: echo "matrix=$(.github/config.py --tags --branches)" | tee $GITHUB_OUTPUT
      - id: latest
        run: echo "latest=$(.github/config.py --latest)" | tee $GITHUB_OUTPUT

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install sphinx
      - run: sphinx-build docs _build
      - uses: actions/upload-artifact@v4
        with:
          name: docs-artifact
          path: _build
          if-no-files-found: error

  build-app:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: [configure, build-docs, build-app]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - uses: actions/download-artifact@v4
      - run: find
      - run: mv docs-artifact/* .
      - run: |
          latest=${{ needs.configure.outputs.latest }}
          echo "<meta http-equiv=\"refresh\" content=\"0; url=$latest\" />" > latest.html
      - run: find
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
           path: .
      - id: deployment
        uses: actions/deploy-pages@v4
